CREATE TABLE IF NOT EXISTS todo (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(255),
	priority INT NOT NULL,
	is_done BOOLEAN NOT NULL DEFAULT 0,
	created TIMESTAMP,
	PRIMARY KEY(id)
);